encryptionsalt: v1:6JCZJ+FPZ/o=:v1:axvmG3ZflvqylUwZ:8J9F+CmjCVz8Z8lY9LhB0PlMHSIk8w==
config:
  aws:profile: joystream-user
  aws:region: us-east-1
  # query-node:membersFilePath: /Users/anuj/Joystream/bootstrap-query-node/members.json
  # query-node:workersFilePath: /Users/anuj/Joystream/bootstrap-query-node/workers.json
