[workspace]
members = [
	"runtime",
	"runtime-modules/proposals/engine",
	"runtime-modules/proposals/codex",
	"runtime-modules/proposals/discussion",
	"runtime-modules/common",
	"runtime-modules/council",
	"runtime-modules/forum",
	"runtime-modules/membership",
	"runtime-modules/memo",
	"runtime-modules/referendum",
	"runtime-modules/service-discovery",
	"runtime-modules/storage",
	"runtime-modules/working-group",
	"runtime-modules/content-directory",
	"runtime-modules/constitution",
	"runtime-modules/staking-handler",
	"runtime-modules/bounty",
    "runtime-modules/blog",
    "runtime-modules/utility",
	"node",
	"utils/chain-spec-builder/"
#    "analyses/bench" # doesn't work with the "all features" release build
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
