[package]
authors = ['Joystream contributors']
build = 'build.rs'
edition = '2018'
name = 'chain-spec-builder'
version = '3.1.1'

[dependencies]
enum-utils = "0.1.2"
ansi_term = "0.12.1"
rand = "0.7.2"
structopt = "0.3.8"
sc-keystore = { git = 'https://github.com/paritytech/substrate.git', rev = 'a200cdb93c6af5763b9c7bf313fa708764ac88ca' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate.git', rev = 'a200cdb93c6af5763b9c7bf313fa708764ac88ca' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate.git', rev = 'a200cdb93c6af5763b9c7bf313fa708764ac88ca' }
sp-core = { git = 'https://github.com/paritytech/substrate.git', rev = 'a200cdb93c6af5763b9c7bf313fa708764ac88ca' }
joystream-node = { path = "../../node" }
