[package]
authors = ['Joystream contributors']
build = 'build.rs'
edition = '2018'
name = 'chain-spec-builder'
version = '5.0.0'

[dependencies]
enum-utils = "0.1.2"
async-std = {version = "1.9.0", features = ["attributes"]}
futures-util = "0.3.15"
ansi_term = "0.12.1"
rand = "0.7.2"
structopt = "0.3.8"
sc-keystore = { git = 'https://github.com/paritytech/substrate.git', rev = '6cbe1772bf258793fa9845daa8f43ea0cadee596' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate.git', rev = '6cbe1772bf258793fa9845daa8f43ea0cadee596' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate.git', rev = '6cbe1772bf258793fa9845daa8f43ea0cadee596' }
sp-core = { git = 'https://github.com/paritytech/substrate.git', rev = '6cbe1772bf258793fa9845daa8f43ea0cadee596' }
sp-keystore = { git = 'https://github.com/paritytech/substrate.git', rev = '6cbe1772bf258793fa9845daa8f43ea0cadee596' }
joystream-node = { path = "../../node" }
