endpoints:
  queryNode: http://graphql-server-mnt:4002/graphql
  substrateNode: ws://joystream-node:9944
directories:
  data: /data
  cache: /cache
  logs: /logs
log:
  file: debug
  console: debug
port: 3334
keys: [//Alice]
buckets: [1]
