id: test-node
endpoints:
  queryNode: http://localhost:8081/graphql
  substrateNode: ws://localhost:9944
  # elasticSearch: http://localhost:9200
directories:
  data: ./local/data
  cache: ./local/cache
  logs: ./local/logs
log:
  file: debug
  console: info
  # elastic: info
limits:
  storage: 100G
  maxConcurrentStorageNodeDownloads: 100
  maxConcurrentOutboundConnections: 300
  outboundRequestsTimeout: 5000
port: 3334
keys: [//Alice]
buckets: 'all'
workerId: 0
