name: joystream-node-checks
on:
  pull_request:

jobs:
  checks:
    name: joystream-node checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            node
            runtime-modules
            utils/chain-spec-builder
          SUFFIX_FILTER: |
            .rs
          FILES: |
            Cargo.lock
            Cargo.toml

      # TODO: Look for change in source code but no corresponding version bump of runtime or binaries
      # - name: Check version modified correctly
      #   if: env.GIT_DIFF

      - name: Build joystream-node (with benchmarking)
        run: |
          # Install required toolchains
          ./setup.sh
          # Build including benchmarks
          pushd node
          WASM_BUILD_TOOLCHAIN=nightly-2020-10-06 cargo build --release --features runtime-benchmarks
          popd
          ./scripts/generate-weights.sh
          # Show any changes in computed weights
          git diff
        if: env.GIT_DIFF